# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date
# within the migration file as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
timezone = UTC

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment file as a
# standalone script, that is, without connecting
# to a database.
# standalone_mode = false

# set to 'true' to use transaction per migration, rather
# than the default behavior of 'transaction_per_migration'
# transaction_per_migration = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory.  These files have timestamp
# information before 3.5 and may break reordering
# operations
# sourceless = false

# if this is set to 'true', the .pyc and .pyo files
# corresponding to .py files in the versions/ directory
# will be automatically removed when the .py file
# is removed
# remove_sourceless_revisions = false

# version location specification; this defaults
# to alembic/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path
version_locations = %(here)s/alembic/versions

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

# the revision environment file to use; this defaults
# to env.py
revision_environment = true

# Controls how many migrations will be walked back
# when calculating the target revision for --autogenerate
# autogenerate_max_cycle_length = 10

# Controls how many migrations will be walked back
# when calculating the target revision for --autogenerate
# autogenerate_skip_revisions = head

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S